--------------------------------------------------------
--  DDL for Table DRPS
--------------------------------------------------------

  CREATE TABLE "SIPRO"."DRPS" 
   (	"TICKER" VARCHAR2(26), 
	"PHONE" VARCHAR2(26), 
	"DRP" VARCHAR2(26), 
	"PARTOPT" VARCHAR2(26), 
	"CASHOPT" VARCHAR2(26), 
	"CAPLUSOPT" VARCHAR2(26), 
	"DIRECT" VARCHAR2(26), 
	"DIRECTMIN" VARCHAR2(26), 
	"CASH" VARCHAR2(26), 
	"CASHFREQ" VARCHAR2(26), 
	"CASHMAX" VARCHAR2(26), 
	"CASHMIN" VARCHAR2(26), 
	"BROKER" VARCHAR2(26), 
	"SERVCHRG" VARCHAR2(26), 
	"DISCOUNT" VARCHAR2(26), 
	"PHONEAGENT" VARCHAR2(26), 
	"INVEST" VARCHAR2(26), 
	"QUALIFY" VARCHAR2(26)
   ) ;
