--------------------------------------------------------
--  File created - Sunday-November-24-2019   
--------------------------------------------------------
@C:\01-MySoftware\tabexp\ALSMAST.sql
@C:\01-MySoftware\tabexp\DATADICT.sql
@C:\01-MySoftware\tabexp\DDVIEWS.sql
@C:\01-MySoftware\tabexp\DRPS.sql
@C:\01-MySoftware\tabexp\FILEMAST.sql
@C:\01-MySoftware\tabexp\INDXMAST.sql
@C:\01-MySoftware\tabexp\LISTMAST.sql
@C:\01-MySoftware\tabexp\RELATION.sql
@C:\01-MySoftware\tabexp\SI_AVG.sql
@C:\01-MySoftware\tabexp\SI_BSA.sql
@C:\01-MySoftware\tabexp\SI_BSQ.sql
@C:\01-MySoftware\tabexp\SI_CFA.sql
@C:\01-MySoftware\tabexp\SI_CFQ.sql
@C:\01-MySoftware\tabexp\SI_CI.sql
@C:\01-MySoftware\tabexp\SI_DOW.sql
@C:\01-MySoftware\tabexp\SI_EE.sql
@C:\01-MySoftware\tabexp\SI_EXCHG.sql
@C:\01-MySoftware\tabexp\SI_GR.sql
@C:\01-MySoftware\tabexp\SI_ISA.sql
@C:\01-MySoftware\tabexp\SI_ISQ.sql
@C:\01-MySoftware\tabexp\SI_MGAV2.sql
@C:\01-MySoftware\tabexp\SI_MGAVG.sql
@C:\01-MySoftware\tabexp\SI_MGDSC.sql
@C:\01-MySoftware\tabexp\SI_MLT.sql
@C:\01-MySoftware\tabexp\SI_PERC.sql
@C:\01-MySoftware\tabexp\SI_PSD.sql
@C:\01-MySoftware\tabexp\SI_PSDA.sql
@C:\01-MySoftware\tabexp\SI_PSDC.sql
@C:\01-MySoftware\tabexp\SI_PSDD.sql
@C:\01-MySoftware\tabexp\SI_PSDH.sql
@C:\01-MySoftware\tabexp\SI_PSDL.sql
@C:\01-MySoftware\tabexp\SI_PSDV.sql
@C:\01-MySoftware\tabexp\SI_PTYP.sql
@C:\01-MySoftware\tabexp\SI_RAT.sql
@C:\01-MySoftware\tabexp\SI_SP.sql
@C:\01-MySoftware\tabexp\SI_TRBCS.sql
@C:\01-MySoftware\tabexp\SI_UDF.sql
@C:\01-MySoftware\tabexp\SI_UTYP.sql
@C:\01-MySoftware\tabexp\SI_VAL.sql
@C:\01-MySoftware\tabexp\STDVIEW.sql
