--------------------------------------------------------
--  DDL for Table DATADICT
--------------------------------------------------------

DROP TABLE SIPRO.DATADICT_EXT;
CREATE TABLE "SIPRO"."DATADICT_EXT" 
(	
   "FILE_NAME" 			VARCHAR2(26 BYTE), 
	"FIELD_NUM" 		CHAR, 
	"FIELD_NAME" 		VARCHAR2(26 BYTE), 
	"FIELD_TYPE" 		VARCHAR2(26 BYTE), 
	"FIELD_LEN" 		CHAR, 
	"FIELD_DEC" 		CHAR, 
	"FIELD_DESC" 		VARCHAR2(128 BYTE), 
	"SORT" 				VARCHAR2(26 BYTE), 
	"REL_REPORT" 		VARCHAR2(26 BYTE), 
	"REPORT" 			VARCHAR2(26 BYTE), 
	"LABELS" 			VARCHAR2(26 BYTE), 
	"MERGE" 			VARCHAR2(26 BYTE), 
	"NULL_Z" 			VARCHAR2(26 BYTE), 
	"PICTURE" 			VARCHAR2(128 BYTE), 
	"DEFAULT_Z" 		VARCHAR2(26 BYTE), 
	"WHEN" 				VARCHAR2(26 BYTE), 
	"VALID" 			VARCHAR2(26 BYTE), 
	"MESSAGE" 			VARCHAR2(26 BYTE), 
	"ERROR" 			VARCHAR2(26 BYTE), 
	"RANGELO" 			VARCHAR2(26 BYTE), 
	"RANGEHI" 			VARCHAR2(26 BYTE), 
	"COMMENTS" 			VARCHAR2(128 BYTE), 
	"CALC_EXPR" 		VARCHAR2(26 BYTE), 
	"HELP" 				VARCHAR2(26 BYTE), 
	"PREV_NAME" 		VARCHAR2(26 BYTE), 
	"CPNOTRANS" 		VARCHAR2(26 BYTE), 
	"SI_TYPE" 			VARCHAR2(26 BYTE), 
	"SI_CALC" 			VARCHAR2(26 BYTE)
)
ORGANIZATION EXTERNAL ( TYPE oracle_loader
    DEFAULT DIRECTORY "STOCK_INVESTOR_PRO" ACCESS PARAMETERS 
    (
        RECORDS DELIMITED BY NEWLINE
        FIELDS TERMINATED BY '|' MISSING FIELD VALUES ARE NULL 
        (
			"FILE_NAME" 		CHAR(26), 
			"FIELD_NUM" 		CHAR, 
			"FIELD_NAME" 		CHAR(26), 
			"FIELD_TYPE" 		CHAR(26), 
			"FIELD_LEN" 		CHAR, 
			"FIELD_DEC" 		CHAR, 
			"FIELD_DESC" 		CHAR(128), 
			"SORT" 				CHAR(26), 
			"REL_REPORT" 		CHAR(26), 
			"REPORT" 			CHAR(26), 
			"LABELS" 			CHAR(26), 
			"MERGE" 			CHAR(26), 
			"NULL_Z" 			CHAR(26), 
			"PICTURE" 			CHAR(128), 
			"DEFAULT_Z" 		CHAR(26), 
			"WHEN" 				CHAR(26), 
			"VALID" 			CHAR(26), 
			"MESSAGE" 			CHAR(26), 
			"ERROR" 			CHAR(26), 
			"RANGELO" 			CHAR(26), 
			"RANGEHI" 			CHAR(26), 
			"COMMENTS" 			CHAR(128), 
			"CALC_EXPR" 		CHAR(26), 
			"HELP" 				CHAR(26), 
			"PREV_NAME" 		CHAR(26), 
			"CPNOTRANS" 		CHAR(26), 
			"SI_TYPE" 			CHAR(26), 
			"SI_CALC" 			CHAR(26)
		)
    ) LOCATION ( 'datadict.csv' )
) REJECT LIMIT UNLIMITED;
