--------------------------------------------------------
--  DDL for Table SI_PSDA
--------------------------------------------------------

DROP TABLE SIPRO.SI_PSDA_EXT;
CREATE TABLE "SIPRO"."SI_PSDA_EXT" 
(	
   	"COMPANY_ID" 	VARCHAR2(26), 
	"PRICE_Y1" 		NUMBER(38,3), 
	"PRICE_Y2" 		NUMBER(38,3), 
	"PRICE_Y3" 		NUMBER(38,3), 
	"PRICE_Y4" 		NUMBER(38,3), 
	"PRICE_Y5" 		NUMBER(38,2), 
	"PRICE_Y6" 		NUMBER(38,3), 
	"PRICE_Y7" 		NUMBER(38,3), 
	"PRICEH_Y1" 	NUMBER(38,3), 
	"PRICEH_Y2" 	NUMBER(38,3), 
	"PRICEH_Y3" 	NUMBER(38,3), 
	"PRICEH_Y4" 	NUMBER(38,3), 
	"PRICEH_Y5" 	NUMBER(38,3), 
	"PRICEH_Y6" 	NUMBER(38,3), 
	"PRICEH_Y7" 	NUMBER(38,3), 
	"PRICEL_Y1" 	NUMBER(38,3), 
	"PRICEL_Y2" 	NUMBER(38,3), 
	"PRICEL_Y3" 	NUMBER(38,3), 
	"PRICEL_Y4" 	NUMBER(38,3), 
	"PRICEL_Y5" 	NUMBER(38,3), 
	"PRICEL_Y6" 	NUMBER(38,3), 
	"PRICEL_Y7" 	NUMBER(38,3), 
	"PRICEV_Y1" 	NUMBER(38,3), 
	"PRICEV_Y2" 	NUMBER(38,3), 
	"PRICEV_Y3" 	NUMBER(38,3), 
	"PRICEV_Y4" 	NUMBER(38,3), 
	"PRICEV_Y5" 	NUMBER(38,3), 
	"PRICEV_Y6" 	NUMBER(38,3), 
	"PRICEV_Y7" 	NUMBER(38,3)
) 
ORGANIZATION EXTERNAL ( TYPE oracle_loader
    DEFAULT DIRECTORY "STOCK_INVESTOR_PRO" ACCESS PARAMETERS 
    (
        RECORDS DELIMITED BY NEWLINE
        FIELDS TERMINATED BY '|' MISSING FIELD VALUES ARE NULL 
        (
		   	"COMPANY_ID" 	CHAR, 
			"PRICE_Y1" 		CHAR, 
			"PRICE_Y2" 		CHAR, 
			"PRICE_Y3" 		CHAR, 
			"PRICE_Y4" 		CHAR, 
			"PRICE_Y5" 		CHAR, 
			"PRICE_Y6" 		CHAR, 
			"PRICE_Y7" 		CHAR, 
			"PRICEH_Y1" 	CHAR, 
			"PRICEH_Y2" 	CHAR, 
			"PRICEH_Y3" 	CHAR, 
			"PRICEH_Y4" 	CHAR, 
			"PRICEH_Y5" 	CHAR, 
			"PRICEH_Y6" 	CHAR, 
			"PRICEH_Y7" 	CHAR, 
			"PRICEL_Y1" 	CHAR, 
			"PRICEL_Y2" 	CHAR, 
			"PRICEL_Y3" 	CHAR, 
			"PRICEL_Y4" 	CHAR, 
			"PRICEL_Y5" 	CHAR, 
			"PRICEL_Y6" 	CHAR, 
			"PRICEL_Y7" 	CHAR, 
			"PRICEV_Y1" 	CHAR, 
			"PRICEV_Y2" 	CHAR, 
			"PRICEV_Y3" 	CHAR, 
			"PRICEV_Y4" 	CHAR, 
			"PRICEV_Y5" 	CHAR, 
			"PRICEV_Y6" 	CHAR, 
			"PRICEV_Y7" 	CHAR
		)
    ) LOCATION ( 'si_psda.csv' )
) REJECT LIMIT UNLIMITED;

